### ISSUE TITLE
Pairwise distance matrices and their comparison

### ISSUE THREAD

**Issue by hinada** [ahof1704/VocalMat#11]
Hi, I'd like to make figures of Pairwise distance matrices and their comparison in  Fig 5B and Fig 5C in the eLife paper, at p10. I have identified variables needed. How can I make those figures?

**Comment by hinada** [comment]
Hi Antonio,

Thank you for your reply. However, what I want to know is how to make matrix figures of Pairwise distance matrices and their comparison. Your comment is to show the diffusion map in 3D. In a default setting, matrix figures are neither shown nor saved. Do I have to make matrix figures manually using the variables you indicated? Is there any option to show and save matrix figures?

**Comment by ahof1704** [comment]
Yes, the figures have to be made manually with the values stored in the
Matlab variables. The figures could be plotted directly in Matlab, but the
current version of the code does not offer that as an option. I would be
glad to point out some resources to help you to code the heat map plot, if
you'd like to do so.

Best
Antonio

**Comment by hinada** [comment]
Hi Antonio,

Thank you for your reply. I guessed I can use the heatmap() function of MATLAB and valuables dist_X1 and dist_X2 in kernel_alignment.m to make matrix figures of Pairwise distance matrices for each group. For the preparation of comparison of Pairwise distance matrices, I guess I have to use the corrcoef() function and each dist_X[i] valuable one by one. Am I correct?

**Comment by ahof1704** [comment]
Correct, you can use Matlab's heatmap function to obtain the pairwise distance plot (figure 5b). Then, for the similarity plot (5c), you should compute the correlation between the two matrices as a whole, not value by value. Such correlation is computed in the kernel_alignment function as shown below https://github.com/ahof1704/VocalMat/blob/9384fabfc1fbd9bc0ef8ca460b652e72c5b6819f/vocalmat_analysis/kernel_alignment.m#L766.

**Comment by hinada** [comment]
Got it! Thank you so much!
