### ISSUE TITLE
All_axes folder not appearing

### ISSUE THREAD

**Issue by cmlenell1** [ahof1704/VocalMat#12]
Hello, I installed the program and ran on several files but for some reason the "all_axes" folder is missing from the outputs. Everything else seems to be working fine. Do you have any suggestions?

**Comment by cmlenell1** [comment]
Hello, I installed the program and ran on several files but for some reason the "all_axes" folder is missing from the outputs. Everything else seems to be working fine. Do you have any suggestions?

**Comment by ahof1704** [comment]
Hi,

The all_axes folder should be created when you call for the vocalmat_classifier function as seen here. https://github.com/ahof1704/VocalMat/blob/9384fabfc1fbd9bc0ef8ca460b652e72c5b6819f/vocalmat_classifier/vocalmat_classifier.m#L214

Do you get any error messages in your prompt? While OS are you using?

**Comment by cmlenell1** [comment]
Hi, I don't have any related errors. I attached screenshots of the matlab code running the file. 
![matlab1](https://user-images.githubusercontent.com/45463545/147671796-4a54ae47-9035-4655-8f2f-891da926dd49.PNG)
![matlab2](https://user-images.githubusercontent.com/45463545/147671798-b2fbaec5-ba71-4e9b-8c4b-654eb857f9a6.PNG)

**Comment by ahof1704** [comment]
Have you changed the "save_plot_spectrograms" to "1" (which means you want the spectrograms to be saved). Note that it is "0" by default.

https://github.com/ahof1704/VocalMat/blob/9384fabfc1fbd9bc0ef8ca460b652e72c5b6819f/VocalMat.m#L30

**Comment by cmlenell1** [comment]
That fixed it. Thanks so much!

As a side question, do you recommend manually reviewing usv categories that have a certain probability to avoid misclassifying ~14% of the usvs?

**Comment by ahof1704** [comment]
I would recommend having a general inspection of the detected and classified USVs, just to make sure things are working properly (ie, evaluate if you had too much noise in your recordings and if that is interfering with detection and classification of the USVs). Once you verify that things are working as expected, you can double-check the USVs classified as one of the less common categories (see [Fig.4c of the paper](https://iiif.elifesciences.org/lax:59161%2Felife-59161-fig4-v2.tif/full/1500,/0/default.jpg)) or with probabilities lower than 85%. 

Good luck!
