### ISSUE TITLE
48kHz audio can't run identifier?

### ISSUE THREAD

**Issue by Hobart10** [ahof1704/VocalMat#13]
HI,
I know that VocalMat recommends Fmax=125kHz, but in trying to apply it to monkey's calls,  errors reported when VocalMat Identifier computing the spectrogram:

`Error using stretchlim
Expected input number 1, I or RGB, to be nonempty.

Error in stretchlim>ParseInputs (line 84)
validateattributes(img, {'uint8', 'uint16', 'double', 'int16', 'single'}, {'real', ...

Error in stretchlim (line 41)
[img,tol] = ParseInputs(varargin{:});

Error in imadjust>parseInputs (line 228)
    lowhigh_in = stretchlim(img);

Error in imadjust (line 105)
    parseInputs(varargin{:});

Error in vocalmat_identifier (line 153)
    B = imadjust(imcomplement(abs(A)./max(abs(A(:)))));

Error in run (line 91)
evalin('caller', strcat(script, ';'));

Error in VocalMat (line 98)
cd(fullfile(root_path, 'audios')); run('vocalmat_identifier.m')`

**Comment by ahof1704** [comment]
Hi, 

For a different frequency range, you will need to make more modifications to the Identifier code. For example, the current pipeline[ removes most of the audible range (<45khz)](https://github.com/ahof1704/VocalMat/blob/5be886dc611e90e41a9b8c2ee428a69c9d6ebcf0/vocalmat_identifier/vocalmat_identifier.m#L135), which in your case, would result in a very narrow frequency band between 45 and 48kHz. This might be the cause of the error you are experiencing, but we would need more information for a proper diagnosis. Start by changing that. You can replace that line of the code by a different cutoff value, such as `min_freq  = find(F>5000);` and see if the error changes.
