### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by Spiroxillin** [ahof1704/VocalMat#14]
Hello,
Thanks for developing this great tool.
I'm getting couple of errors in the end of the analysis and wants to check if there are any reasons to be concerned about it.
This this the errors I get:

plotting for sigma= 0.5...
Error using diffusion_maps
Invalid expression. Check for missing multiplication operator, missing or unbalanced delimiters, or other
syntax error. To construct matrices, use brackets instead of parentheses.

Error in run (line 91)
evalin('caller', strcat(script, ';'));

Error in VocalMat (line 110)
cd(analysis_path); run('diffusion_maps.m')

I will appreciate your help.

**Comment by ahof1704** [comment]
Hi,

Looks like there is something missing in your script. Perhaps a typo. Can you please compare your version to the original script? More specifically this [line](https://github.com/ahof1704/VocalMat/blob/5be886dc611e90e41a9b8c2ee428a69c9d6ebcf0/vocalmat_analysis/diffusion_maps.m#L33). As the error message suggested, please check for missing brackets or parentheses.

I hope it helps.
Best
