### ISSUE TITLE
Unable to perform assignment because the indices on the left side are not compatible with the size of the right side.

### ISSUE THREAD

**Issue by Aiwynn** [ahof1704/VocalMat#15]
Hello. 
Thank you for sharing your code :)
After running it with the example audio, I get the error: 

>Unable to perform assignment because the indices on the left side are not compatible with the size of the right side.

>Error in diffusion_maps (line 35)
>eval(['maps_' vfilename '= maps;']) 

>Error in run (line 91)
>evalin('caller', strcat(script, ';'));

I understand it is because the char 'vfilename' and the array 'maps' do not have the same size, but I do not know how to solve this issue. How should I resolve this? 

I still get some of the output files, the 2 excel files and the folder named "All" with all the pictures inside it.

Thanks in advance :)

**Comment by ahof1704** [comment]
Hi,

Yes, the problem seems to be associated with the fact that you don't  the same variable size 'maps' and 'vfilename'. The big question is why this is happening. Can you check what is the size and length of the variables 'maps' and 'vfilename'? 

Also, this is only needed if you intend to compute diffusion maps (ie, embedding the USVs to a 3D space). If you don't need that, you can simply comment out that part of the code. 

Best.

**Comment by Aiwynn** [comment]
Thank you for answering so fast. :) 

Matlab tells me the variable 'maps' is an 89x3 single and the variable 'vfilename' is a 1x17 char. 
Where could I change their size?

**Comment by ahof1704** [comment]
The 'maps' and 'vfilename' seem to have the correct shapes and data types. 
Maybe it is a problem with the name of the file you are using. Are you using any special characters, symbols or space in 'vfilename'?

**Comment by Aiwynn** [comment]
There were parenthesis in the file name, I removed them, and it was able to run! :) Thank you! 
Although I am missing the folder called "All-axes" with all the axed vocalizations graphs in the output folder.

**Comment by ahof1704** [comment]
Glad to hear it is working now! 
To obtain the USVs with the axes, make sure the [save_plot_specrograms].(https://github.com/ahof1704/VocalMat/blob/5be886dc611e90e41a9b8c2ee428a69c9d6ebcf0/VocalMat.m#L30) is set to '1'. It is is '0'(ie, to not save the axes) by default. 
`save_plot_specrograms = 1; % plots the spectograms with axis`

**Comment by Aiwynn** [comment]
Amazing, thank you so much! :D

**Comment by ahof1704** [comment]
Awesome. Have fun! :)
