### ISSUE TITLE
USVs detected in absence of mice

### ISSUE THREAD

**Issue by gabbyblah** [ahof1704/VocalMat#21]
Hello! I ran a file today on an empty restraint device (no mouse in it), but oddly VocalMat picked up what looked to be like 10-15 total USVs (which, of course, there weren’t - or at least shouldn't have been - any). This is nearly five times the number that we’ve been seeing in analysis of recordings of our actual mice, so we are curious whether this is a result of background noise in the absence of any actual USVs. I would really appreciate hearing any thoughts that you may have regarding this issue and how we may troubleshoot - is there a way to calibrate for the background noise? Is it simply just the result of picking up any noise when there are no vocalizations? Thank you for this awesome tool and any help you can provide!

**Comment by ahof1704** [comment]
Hi, VocalMat automatically learns to differentiate background noise from USVs. This assumes that there are USVs in the recording. In the case of a recording of an empty device, this is most likely noise. Can you please check the following?
1) Take a look at the saved spectrograms. These 10-15 USVs should not look like USVs (hopefully you don't have ghost mice!) 
2) Check the saved Excel file for the classification and final labels. You will likely see that the 15 detected USVs had low scores for the USV of a given class. 

Feel free to share the files mentioned above and we can go from there. 

Good luck.

**Comment by ahof1704** [comment]
Closed due to inactivity
