### ISSUE TITLE
Composition of Audio Example file

### ISSUE THREAD

**Issue by srawlins05** [ahof1704/VocalMat#22]
Hello! I hope this message finds you well. I'm wondering if you're able to provide some more information on the example audio file on this website? Is the audio example a recording of a mouse / rodent and its vocalizations? A recording of a various, known rodent USVs? Either way, under what conditions was the 10 minute recording run? We are using the audio example file as a baseline for our vocal analysis - it helps us to shape our understanding of what the kind / frequency of speech that should be expecting from our mice - and it would be helpful to know the experimental conditions for that file. Thank you!

**Comment by ahof1704** [comment]
Hi!

The audio file we provide as an example consists of a mouse pup recorded in isolation. You can find more information about the background of the mice and the experimental setup in the 'Materials and Methods' section of the paper [1].

Regarding what you should expect for the vocalization rate of your animals, it may depend on several factors such as strain, age, sex and context, as other studies have pointed out [2,3]

[1] https://elifesciences.org/articles/59161
[2] https://onlinelibrary.wiley.com/doi/10.1111/gbb.12815
[3] https://www.nature.com/articles/s41598-023-31554-3

**Comment by srawlins05** [comment]
Hi Dr. Fonseca, thanks so much for your prompt reply. This information and these links are very helpful!

**Comment by idala03** [comment]
Hello! I'm having a similar issue in that I get error messages when trying my wave file. The sample file works fine! I just get error messages about the diffusion maps script when trying my wave file. Do you have any advice? The sampling size for my file is 250 kHz, as suggested; it has a shorter duration, one channel, and with less total samples than the example. Our files do not have that much background noise. Could that be the issue? What are your suggestions for modifying preprocessing steps or changing parameters in the code?
Thank you so much!

**Comment by idala03** [comment]
<img width="901" alt="Screenshot 2024-06-10 at 15 39 14" src="https://github.com/ahof1704/VocalMat/assets/171709385/ede6e321-f92f-42ad-ac63-eaa581aee58e">
Attached is an image of spectrograms comparing the sample file and the file I want to process, if that's helpful

**Comment by ahof1704** [comment]
This discussion was moved and solved in #23
