### ISSUE TITLE
Parameters unclear

### ISSUE THREAD

**Issue by idala03** [ahof1704/VocalMat#23]
Hello! I'm having an issue using VocalMat to process my wave file. The sample file works fine! I continue to get error messages related to the vocalmat_identifier.m script (specifically around the time it removes small vocalizations). Do you have any advice? The sampling size for my file is 250 kHz, as suggested; it has a shorter duration, one channel, and with less total samples than the example. Our files do not have that much background noise. Could that be the issue? What are your suggestions for modifying preprocessing steps or changing parameters in the code?
Thank you so much!

**Comment by ahof1704** [comment]
What is the error you are getting? 

Are you sure that the recording has any vocalizations in it? The spectrogram you shared on the other thread looks quite silent. I also noticed that you have quite a lot of constant high-frequency noise. Unfortunately, VocalMat is not very good at accounting for this type of noise.

**Comment by idala03** [comment]
Thank you very much for your response! 
The errors I'm getting are the following:

Operation terminated by user during vocalmat_identifier (line 377)


In run (line 112)
evalin('caller', strcat(scriptStem, ';'));

In VocalMat (line 99)
cd(fullfile(root_path, 'audios')); run('vocalmat_identifier.m')
 
I think it's stuck in a loop because I have to stop the code. Also, the data I am using is for mouse pups, and their vocalizations are typically between 5-95 kHz. Perhaps the code cannot account for that range. Is there a way I might be able to modify the code myself to accommodate for that difference? I have checked the file for vocalizations, and they are present, but they last only a few ms, so that could also contribute to the issue. Do you think it would be possible to filter the high-frequency noise with a low-pass filter?
Thanks again!

**Comment by ahof1704** [comment]
Here are a few questions: 
- Why are you considering vocalizations at 5khz? Are you working with distress calls? Previous works (for example see [1]) assume the cut-off for minimum frequency at 30khz. VocalMat was trained to handle vocalizations in the range of 45 to 120kHz. You could change the cut-off frequency, but you would need to retrain the classifier if you care about the classification of the detected USVs. 
-  Your file looks oddly silent to me. Could you send some examples of USVs you have manually found on this file? A screenshot showing the vocalization and its corresponding duration and frequency range would be sufficient. Keep in mind we also have a cut-off for minimum duration, such that vocalizations for candidates shorter than 3ms are discarded.
- What is the bandwidth of your noise? Are they in the same range as your USVs? We had problems with noise during our recordings. The most efficient solution was to perform the recordings in soundproof chambers. We can provide more details if you would like to pursue this direction.

[1] https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0017460

**Comment by idala03** [comment]
Thank you so much for all of the tips! I tried a different audio file, and it worked much better—I think there was an issue with that particular file. 
I am also cutting off vocalizations shorter than 10 ms and would love to modify the code to only include USVs with 10 ms separating two vocalizations. 
We are working with mouse pups who have hypoxic ischemia, and we will reconsider our vocalization range! 
I really appreciate all of the resources you are providing.

**Comment by idala03** [comment]
I believe I can manage from here on out—thanks again! I have one more question if you don't mind. The command window records the number of vocalizations and the number that were counted but are just noise. Is it possible to modify the Excel file/the output file to ensure it only includes these "real" vocalizations?

**Comment by ahof1704** [comment]
I think the easiest way would be to filter the Excel file afterwards, in a post-processing step. You could do it either on Matlab or directly on Excel.
