### ISSUE TITLE
Retraining the classifier

### ISSUE THREAD

**Issue by idala03** [ahof1704/VocalMat#25]
Hello! Thank you so much with your help previously with image post-processing. I was hoping to retrain the classifier (or add onto the CNN model) with our audio files. Do you think you could assist me in understanding which script I can run to retrain it with our wav files?

**Comment by ahof1704** [comment]
The script to train the classifier can be found [here](https://github.com/ahof1704/VocalMat/blob/master/vocalmat_classifier/training/train_model.m). 

You should consider merging your samples with the original dataset used to train the current classifier. You can find the dataset in this [link](https://osf.io/bk2uj/).

**Comment by idala03** [comment]
Thank you so much! This was very useful.
