### ISSUE TITLE
Extension files

### ISSUE THREAD

**Issue by mzimmer1988** [ahof1704/VocalMat#4]
We are not able to use different extension files (.WAV or .wav) to run the Vocal mat. Antonio has changed the mult_jobs code and also the identifier. Please, see below the screenshots with these changes.

![mult_jobs](https://user-images.githubusercontent.com/23036284/29932247-c2ec30ee-8e41-11e7-9d79-c6d335ea46dc.png)
![identifier_5b](https://user-images.githubusercontent.com/23036284/29932246-c2e2e8b8-8e41-11e7-8559-e8bde1fd3995.png)

**Comment by ahof1704** [comment]
Solved with last commit.
