### ISSUE TITLE
Undefined function or variable 'max_freq'.

### ISSUE THREAD

**Issue by mzimmer1988** [ahof1704/VocalMat#6]
One of the audios (1795 - 2nd stage) is not running in the VocalMat due to the followed issue (See attached).
![screen shot 2017-09-25 at 11 25 20 am](https://user-images.githubusercontent.com/23036284/30824944-3c214d02-a1ff-11e7-957b-f3d4ccdd4676.png)

**Comment by ahof1704** [comment]
Solved in the last commit (Sept 26th) for Identifier v6.
