### ISSUE TITLE
Training on Rodent Dataset

### ISSUE THREAD

**Issue by gouins** [ahof1704/VocalMat#8]
Hi,
Not so much an issue but I was wondering if it would be possible to train VocalMat on a rodent dataset. I am currently organizing images categorized by each subtype, similar to the OSF repo, to be used. 
Thanks

**Comment by ahof1704** [comment]
Hi Samir,

Yes, you can train VocalMat on your dataset. This is the script you will need to do so:
vocalmat_classifier/training/train_model.m
https://github.com/ahof1704/VocalMat/blob/4f8ee4f6bbf0b5c202bcde7d61430d5d113331a3/vocalmat_classifier/training/train_model.m#L1

Once you have the dataset organized and ready for training, we can walk you through the setup process.

Best
Antonio

**Comment by gouins** [comment]
Great thanks Antonio! We are aiming for at least 1000 images per subtype. Do you think this number is ok?

**Comment by ahof1704** [comment]
It might be a low N for the call types with a high degree of variability, but that's a good start 👍

**Comment by gouins** [comment]
Alright, I will try to increase this. Does any image format work or is png preferred?

**Comment by ahof1704** [comment]
It should work with most of the popular image formats (bmp, jpg, png, tif, etc).

**Comment by gouins** [comment]
Thanks, our photos currently look like this (white background with black call & with axis). Should the axis be cropped out? 
<img width="368" alt="Screen Shot 2020-07-29 at 11 48 21 PM" src="https://user-images.githubusercontent.com/65608691/88878419-f244a880-d1f5-11ea-8aa5-13ca235f83e7.png">

**Comment by gouins** [comment]
^ in case you missed it

**Comment by ahof1704** [comment]
Oh Sorry! I missed that. Yes, remove the axes. Are all the images scaled with the same frequency range and time window?

**Comment by gouins** [comment]
Ok, thanks. The frequency range is fixed (0-125kHz). The time range is not.

**Comment by ahof1704** [comment]
To use our framework, you will need to set the same time window for all the images. Ideally, the time window should be set as at least 50% longer than the longest USV you have found in your dataset. This will prevent eventual crops of the long USVs. Since the machine learning component receives only images as inputs, setting the images to represent the same window size is an important step of the process, which in our case is done by the "Identifier" in our pipeline.

**Comment by gouins** [comment]
Thanks, going to try and find a solution

**Comment by ahof1704** [comment]
I would suggest adapting the [Identifier](vocalmat_identifier/vocalmat_identifier.m) code to do this task for you and prepare the samples for the classification.

**Comment by gouins** [comment]
Hi Antonio,
Made some progress, what do you think about this?

<img width="433" alt="Screen Shot 2020-08-25 at 9 07 24 PM" src="https://user-images.githubusercontent.com/65608691/91243270-98ad9c00-e717-11ea-98f8-cd16b3ff342b.png">

**Comment by ahof1704** [comment]
Looks good to me. Are you using fixed-width (time interval) and height (frequency range) for the windows now?

**Comment by gouins** [comment]
Yes exactly, thanks! The outline around the photo is ok?

Samir

**Comment by ahof1704** [comment]
I think it shouldn't be a problem, but if removing the outline is an option, I would do so.

**Comment by gouins** [comment]
Hi Antonio, I've been able to gather data to train VocalMat on a rodent subtypes. Would it be possible for me to send you a sample for feedback?

**Comment by ahof1704** [comment]
Yeah absolutely
